"""
note: generated by claude, prompt below; human reviewed and tested:

  running build_pages.py creates a large number of files and takes hours.  
  write a python script that takes a `synonym` input from the user and 
  generates a thumbnail for that synonym but no other files. use 
  the `generate_thumbnail()` function in `building.py`.  


Generate a thumbnail for a single synonym without building any other pages.

"""

import argparse

from build_tools import loading, building
from build_tools.env import THUMBNAILS_DIR

parser = argparse.ArgumentParser(
    description="Generate a thumbnail for a single synonym."
)
parser.add_argument("synonym", help="The synonym name (e.g. 'aIP1')")
parser.add_argument(
    "--overwrite",
    action="store_true",
    help="Regenerate the thumbnail even if it already exists.",
)
args = parser.parse_args()

mcns_meta, fw_meta, _, _ = loading.load_cache_meta_data()

# Find all rows whose synonyms string contains the requested synonym name.
# The synonyms column contains semicolon-separated entries of the form
# "Author Year: SynonymName", so we parse each entry the same way
# make_synonyms_pages() does.
body_ids = []
root_ids = []

for df, id_col in [(mcns_meta, "bodyId"), (fw_meta, "root_id")]:
    for _, row in df.iterrows():
        raw = row.get("synonyms")
        if not isinstance(raw, str):
            continue
        for entry in raw.split(";"):
            if ":" not in entry:
                continue
            syn_name = entry.split(":", 1)[1].strip()
            if syn_name == args.synonym:
                id_val = row[id_col]
                if id_col == "bodyId":
                    body_ids.append(id_val)
                else:
                    root_ids.append(id_val)
                break  # only count each row once

body_ids = list(set(body_ids))
root_ids = list(set(root_ids))

if not body_ids and not root_ids:
    print(f"No neurons found for synonym '{args.synonym}'.")
    raise SystemExit(1)

print(f"Found {len(body_ids)} MCNS neuron(s) and {len(root_ids)} FlyWire neuron(s).")

file_name = args.synonym.replace(" ", "_").replace("/", "_")
outfile = THUMBNAILS_DIR / f"{file_name}.png"

building.generate_thumbnail(
    mcns_meta[mcns_meta.bodyId.isin(body_ids)],
    fw_meta[fw_meta.root_id.isin(root_ids)],
    outfile,
    skip_existing=not args.overwrite,
)

print(f"Thumbnail written to {outfile}")
