site_name: MaleCNS connectome
site_description: Project website for the MaleCNS connectome
site_url: https://janelia-flyem.github.io/dimorphism-explorer/
# copyright: Copyright &copy; 2025, Howard Hughes Medical Institute


plugins:
  - tags
  - search

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HHMIJanelia
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@hhmi

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Overview: https://www.janelia.org/project-team/flyem/male-cns-connectome
  - Explore:
      - Overview: explore/index.md
  - Dimorphism: build/dimorphism_overview.md
  - Download: download.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - header.autohide
    - content.tooltips
  logo: assets/flyem_logo_white.svg
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.details
  - tables
  - pymdownx.superfences
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
